// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqn-H8LIdN9AFYu8AZntjObsTX25YNyg0',
    appId: '1:383966618673:web:d485fbd512b36aa897a110',
    messagingSenderId: '383966618673',
    projectId: 'tcc-vincenzo-joao',
    authDomain: 'tcc-vincenzo-joao.firebaseapp.com',
    databaseURL: 'https://tcc-vincenzo-joao-default-rtdb.firebaseio.com',
    storageBucket: 'tcc-vincenzo-joao.firebasestorage.app',
    measurementId: 'G-JVZRG80NN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD89vHbC_7UeeyI6ldCcz02k3vQW7VqSys',
    appId: '1:383966618673:android:77f9916169af6d3e97a110',
    messagingSenderId: '383966618673',
    projectId: 'tcc-vincenzo-joao',
    databaseURL: 'https://tcc-vincenzo-joao-default-rtdb.firebaseio.com',
    storageBucket: 'tcc-vincenzo-joao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMejguyRdc4ZEeXfHH6zZvL-4wdq-0Rc4',
    appId: '1:383966618673:ios:e05d9d6fadc22b9f97a110',
    messagingSenderId: '383966618673',
    projectId: 'tcc-vincenzo-joao',
    databaseURL: 'https://tcc-vincenzo-joao-default-rtdb.firebaseio.com',
    storageBucket: 'tcc-vincenzo-joao.firebasestorage.app',
    androidClientId: '383966618673-jcd1mdiuhoj3voe5o9ccolo0bsimnb9n.apps.googleusercontent.com',
    iosClientId: '383966618673-l2b559ofu7ftrrjv7bgpe5r6agt1jirq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tcc1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMejguyRdc4ZEeXfHH6zZvL-4wdq-0Rc4',
    appId: '1:383966618673:ios:e05d9d6fadc22b9f97a110',
    messagingSenderId: '383966618673',
    projectId: 'tcc-vincenzo-joao',
    databaseURL: 'https://tcc-vincenzo-joao-default-rtdb.firebaseio.com',
    storageBucket: 'tcc-vincenzo-joao.firebasestorage.app',
    androidClientId: '383966618673-jcd1mdiuhoj3voe5o9ccolo0bsimnb9n.apps.googleusercontent.com',
    iosClientId: '383966618673-l2b559ofu7ftrrjv7bgpe5r6agt1jirq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tcc_1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqn-H8LIdN9AFYu8AZntjObsTX25YNyg0',
    appId: '1:383966618673:web:5ae07d81fdcd8a3797a110',
    messagingSenderId: '383966618673',
    projectId: 'tcc-vincenzo-joao',
    authDomain: 'tcc-vincenzo-joao.firebaseapp.com',
    databaseURL: 'https://tcc-vincenzo-joao-default-rtdb.firebaseio.com',
    storageBucket: 'tcc-vincenzo-joao.firebasestorage.app',
    measurementId: 'G-QT3YJFTMJ1',
  );

}